
services:
  - type: web
    name: admanager-middleware
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: ADMANAGER_URL
        value: https://ad360.melabs.tech/admp/RestAPI/SearchUser
      - key: ADMANAGER_TOKEN
        value: 0638b6f2-404d-450a-b56f-4deb8bc36b28
      - key: ADMANAGER_DOMAIN
        value: Produccion.com
    autoDeploy: true
